# Generated by Django 4.1.7 on 2023-05-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210820_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:10 - 10:00', '9:10 - 10:00'), ('10:00 - 10:50', '10:00 - 10:50'), ('11:10 - 12:00', '11:10 - 12:00'), ('12:00 - 12:50', '12:00 - 12:50'), ('01:50 - 02:40', '01:50 - 02:40'), ('02:40 - 03:30', '02:40 - 03:30'), ('3:40 - 4:30', '3:40 - 4:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], default='11:00 - 11:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
