# Generated by Django 4.2.1 on 2023-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_alter_marks_name_alter_marksclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:10 - 10:00', '9:10 - 10:00'), ('10:00 - 10:50', '10:00 - 10:50'), ('11:10 - 12:00', '11:10 - 12:00'), ('12:00 - 12:50', '12:00 - 12:50'), ('01:50 - 02:40', '01:50 - 02:40'), ('02:40 - 03:30', '02:40 - 03:30'), ('3:40 - 4:30', '3:40 - 4:30')], default='9:10 - 10:00', max_length=50),
        ),
    ]
