# Generated by Django 4.2.1 on 2023-05-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_alter_assigntime_day_alter_assigntime_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('recipient_list', models.CharField(max_length=100)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
